#!/bin/bash

JAR_NAME="$1"

cd "$(dirname "$0")"

cd ..

echo "Compiling Test.java with $JAR_NAME..."
javac -cp "$JAR_NAME" tests/Test.java

if [ $? -ne 0 ]; then

    echo "Failed compiling Test.java"
    exit 1

fi

echo "Executing Tests..."

java -cp "$JAR_NAME:tests" Test
